export { CounterButtonPage } from './CounterButtonPage'
export { HomePage } from './HomePage'
export { PeopleListPage } from './PeopleListPage'
export { ControlledFormPage } from './ControlledFormPage'
export { UncontrolledFormPage } from './UncontrolledFormPage'
export { ProtectedPage } from './ProtectedPage'
export { UserProfilePage } from './UserProfilePage'
export { NotFoundPage } from './NotFoundPage'